- index.js
- package.json
This will allow us to lint for `v8` (instead of `V8`) and `Javascript`
(instead of `JavaScript`), etc.
This change will require https://github.com/nodejs/node/pull/17163 in node itself. That PR corrects these issues in the node codebase itself.
> add plugin for forbidden strings

- index.js
- package-lock.json
- package.json
This rule currently finds three errors Node.js core .md files and no
false positives.
> add rule to disallow trailing spaces

- index.js
- package-lock.json
- package.json
> remark-lint-no-blockquote-without-caret
> Deprecated: use remark-lint-no-blockquote-without-marker instead
https://www.npmjs.com/package/remark-lint-no-blockquote-without-caret
> replace caret with marker

- index.js
Refs: https://github.com/nodejs/node/pull/26695#issuecomment-473512021
The first commit prohibits `rfc` and `Rfc` to enforce uppercase `RFC`.
As of https://github.com/nodejs/node/commit/3b6344ce42f35e83a580ef55a19c23becccdaa07 this gives:
```console
doc/api/dns.md
115:65-115:72  warning  Use "RFC" instead of "rfc"  prohibited-strings  remark-lint
558:34-558:41  warning  Use "RFC" instead of "rfc"  prohibited-strings  remark-lint
561:52-561:59  warning  Use "RFC" instead of "rfc"  prohibited-strings  remark-lint
650:65-650:72  warning  Use "RFC" instead of "rfc"  prohibited-strings  remark-lint
1011:34-1011:41  warning  Use "RFC" instead of "rfc"  prohibited-strings  remark-lint
1014:52-1014:59  warning  Use "RFC" instead of "rfc"  prohibited-strings  remark-lint
⚠ 6 warnings
```
The …
> Normalize on `RFC <number>`

- index.js
> add 'UNIX' and 'unix' to list of prohibited strings (should be 'Unix')

- index.js
- package-lock.json
- package.json
This should be OK with https://github.com/nodejs/node/pull/29352, but I'm not sure if there are other affected repos that might also need to be checked/fixed before this can land
> feat: add remark-lint-no-consecutive-blank-lines

- .travis.yml
> Travis CI: specify `depth 1` when cloning the Node.js repo.

- package.json
Releated to #31
Doesn't include tools/doc or test
> chore: Expand CI test globs

- index.js
- package-lock.json
- package.json
Update remark-lint-prohibited-strings@1.5.1 and simplify configuration.
> chore: udpate prohibited strings to 1.5.1

- index.js
I think this used to be in here, so maybe it was dropped for a reason. I think I've mostly seen this in the website content rather than the core
> feat: Add NodeJS to prohibited strings

- .github/workflows/test.yml
Still build on the dependabot PRs
> chore: Don't build dependabot branches

- package-lock.json
- package.json
This fixes a bug that causes remark-preset-lint-node to miss some
errors.
Refs: https://github.com/nodejs/node/pull/33691
> fix: bump remark-lint-prohibited-strings from 1.5.1 to 1.5.2

- README.md
These instructions are no longer relevant due to https://github.com/nodejs/node/pull/34148.
> Remove `Adding a new language to the highlight.js bundle` instructions

- index.js
- package-lock.json
- package.json
- remark-lint-nodejs-yaml-comments.js
Add a linter rule to validate YAML comments in markdown files.
The goal of this PR is to enforce a consistent order convention across the Node.js documentation.
> feat: lint YAML comments in md files

- package-lock.json
- package.json
Some of the plug-ins require v13, so this bumps all the outstanding ones and the CLI
> feat: Upgrade to Remark v13 with plug-ins

- package.json
The current CI missed a pair of README files (one in test and one in
src) in Node.js core.
I expect this to fail until https://github.com/nodejs/node/pull/35905 lands (as it contains a commit that fixes lint errors in the two missed files).
> chore: update CI linting

- package-lock.json
- package.json
- remark-lint-nodejs-yaml-comments.js
Fix call to `safeLoad` that became `load` in v4 https://github.com/nodeca/js-yaml/blob/master/migrate_v3_to_v4.md
Fixes #170
> feat: Bump js-yaml to v4

- index.js
"Node-API" must not trigger the prohibited strings rule that recommends
"Node.js" over "Node".
> feat: allow "-API" to follow "Node"

- README.md
- remark-lint-nodejs-yaml-comments.js
If an environment variable `NODE_RELEASED_VERSIONS` is detected, it is
used to validate the version numbers in the YAML comments. At the
notable exception of version numbers 0.0.x and 0.1.x,  and the
`REPLACEME` placeholder, any value not in the list is reported as
invalid.
The idea is to add a script on the node repo GH actions to parse the changelogs to populate the env variable. It won't change anything for doing local linting, but may help spot version errors when reviewing PRs.
For info, it let me spot https://github.com/nodejs/node/pull/37231 and https://github.com/nodejs/node/pull/37232, and I've seen a few times contributors trying to guess the next release version number because they didn't know about `REPLACEME`.
> feat: allowlist for version numbers in YAML comments

- index.js
It seems ESLint folks are not interested in my meta string proposal, I guess the right move would be to move from
````markdown
```js esm
// ES module
export {};
```
```js cjs
// CJS module
module.exports = {};
```
```js
// Whichever
console.log();
```
````
to
````markdown
```mjs
// ES module
export {};
```
```cjs
// CJS module
module.exports = {};
```
```js
// Whichever
console.log();
```
````
Refs: https://github.com/nodejs/node/pull/37162
Refs: https://github.com/nodejs/node/pull/37311
Refs: https://github.com/eslint/eslint-plugin-markdown/issues/170
---
FWIW, I'd be up to fork the eslint markdown plugin and maintain ourselves support for the meta string instead, but maybe it's not worth the maintenance burden.
> chore: allow cjs and mjs info strings

- .gitignore
tmp is a symlink and not a directory so `tmp/` doesn't work to ignore
it.
> chore: fix gitignore entry for tmp

- index.js
- package-lock.json
- package.json
- remark-lint-nodejs-links.js
Replacement for checkLinks.mjs from the nodejs/node repo. Adds a validation for self-reference links to not contain the name of the file.
> feat: lint links and definitions

- package.json
We now package remark-gfm as part of this plugin so there is no need to
include it with a CLI flag.
> chore: remove unneeded --use gfm from npm scripts

- index.js
- package.json
- test/ok.md
The rules conflicts with the output of remark-gfm, so we end up with a
lot of lint errors when using the preset for formatting markdown. It is
likely to be deprecated.
Ref: https://github.com/remarkjs/remark/discussions/863#discussioncomment-1383476
> fix: disable no-auto-link-without-protocol

- test/test.js
This avoids double reporting of the same error.
```js
[Error: ENOENT: no such file or directory, open '…/test/fixtures/fail-nodejs-yaml-comments.md'] {
errno: -2,
code: 'ENOENT',
syscall: 'open',
path: '…/test/fixtures/fail-nodejs-yaml-comments.md'
}
file://…/test/test.js:28
throw error;
^
Error: The Promise never fulfilled
at mustCall (file://…/test/test.js:19:33)
at file://…/test/test.js:69:11
```
The `The Promise never fulfilled` is not useful, as the error is already reported just above.
> test: skip `mustCall` checks if there's already an error

- package-lock.json
- package.json
Once this lands, all dependencies will be up to date. At that point, I'd like to publish a new minor because the remark-gfm update from several commits ago added the ability to use GFM footnotes, which will be helpful in some node core docs (like BUILDING.md).
Refs: https://github.com/remarkjs/remark-gfm/commit/890005e6253517c575dbd109d7149c16b7c26160
Refs: https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/
We could also publish the new release before that as anyone installing it will still get the most up-to-date remark-lint-prohibited-strings.
> chore: update remark-lint-prohibited-strings to 3.1.0

- index.js
As part of https://github.com/nodejs/nodejs.dev/pull/2092 I needed to change some blocks to `ts` so ESLint can properly parse them, but that currently then fails this rule. We already have some other JS-like languages with `coffee` allowed.
> feat: allow ts blocks for Typescript

- .github/workflows/test.yml
12 is EOL and packages are dropping support now
> ci: replace Node 12 for 18

- .github/workflows/test.yml
BREAKING CHANGE: Drop support for Node.js 14
> chore: update test matrix to drop 14 and add 20

- package-lock.json
Rather than sort out which packages need to be updated together, this updates all of them.
Closes: https://github.com/nodejs/remark-preset-lint-node/pull/438
> build(deps): bump all dependencies

- .github/workflows/test.yml
- package.json
BREAKING CHANGE: requires Node.js 18.x or newer
> chore: drop support for Node.js earlier than 18.x

- index.js
To match eslint settings for JavaScript
> fix: update maximum line length to 120

- index.js
- package-lock.json
- package.json
In the most recent version of the recommended rules, the configuration for remark-lint-list-item-indent was changed to what we use, so we no longer need to include the rule explicitly in our configuration.
Refs: https://github.com/remarkjs/remark-lint/commit/8df41b3c93be7c16082421c54830ab63b6fa0498
> chore: remove rule already included by recommended rules

- package.json
Updating dev dependencies etc. do not require a release. Let's use the default rules, which have worked fine for me on other projects.
> chore: do not release when 'chore' and similar commits

- .github/dependabot.yml
Potentially this could just be one big blob of updates of prod+dev, but I thought splitting it might make sense. This way, the next time there is a ton of remark-lint bumps, we'll only get one PR.
I flipped the cadence for NPM PRs to weekly, since I don't know if there is a need for daily PRs, even with the bundled updates.
> chore: Use Dependabot groups to bundle PRs

- package-lock.json
- package.json
This update means line and column numbers will be reported again for errors with trailing spaces.
> chore: update remark-lint-no-trailing-spaces from 2.0.1 to 3.0.0

- .github/workflows/test-and-release.yml
There's a bug in Node.js 22.5.0 that causes the npm installation step to fail. Pin testing to 22.4 until a fix comes out.
> chore: pin Node.js test to 22.4 to avoid npm failures

- .github/workflows/test-and-release.yml
Reverts nodejs/remark-preset-lint-node#575
DNM, just opening as a reminder for when 22.5.x comes out
> Revert "chore: pin Node.js test to 22.4 to avoid npm failures"
