nodejs/remark-preset-lint-node

- index.js
update index.js to the version currently used in Node.js master branch
> sync strings with current node repo settings

- index.js
Refs: https://github.com/nodejs/node/pull/26251
> add End-Of-Life to prohibited strings

- index.js
- package-lock.json
- package.json
Node was normalized in https://github.com/nodejs/node/commit/e2dcbf1c3231513c38151d729f180a54ea902da9
> feat: add remark-lint-unordered-list-marker-style

- .github/workflows/test.yml
- .travis.yml
- README.md
- package.json
Draft because I'm not sure if the `nodejs` organization has access to GitHub Actions yet, and if they are enabled for this repo.
Note that I had to remove the `test` directory.
> Switch to GitHub Actions CI.

- package-lock.json
Flattens the deps tree.
197 -> 185 packages.
> Regenerate package-lock.json.

- index.js
Refs: https://github.com/nodejs/node/pull/30758
> add Node as prohibited string in favor of Node.js

- index.js
CI won't pass until https://github.com/nodejs/node/pull/31326 is merged.
> add rule for "host name" over "hostname" in prose

- index.js
- package.json
Upstream PR to fix https://github.com/nodejs/node/pull/32676
> feat: enable remark-lint-no-literal-urls

- index.js
Was just checking to compare the rules an noticed the file has moved upstream
> doc: Update link to style guide in node repo

- README.md
> Add new language or grammar instructions

- README.md
These instructions are relevant due to https://github.com/nodejs/node/pull/34024.
> Add `Adding the language to the documentation style guide` instructions

- remark-lint-nodejs-yaml-comments.js
Refs: https://github.com/nodejs/node/pull/38324
> feat: validate illformed YAML comments

- index.js
We'll need these to land before this passes CI, but approvals prior to that would be welcome:
Refs: https://github.com/nodejs/node/pull/38841
Refs: https://github.com/nodejs/node/pull/38839
> feat: add linting for "Long Term Support"

- README.md
- index.js
- package-lock.json
- package.json
- test/fail.md
The previous version had a bug where it...uh...didn't actually lint
anything. We've added a test now to at least make sure errors are
reported.
@aduh95 @nschonni @nodejs/linting
> fix: detect lint errors

- package-lock.json
This bumps a bunch of remark-lint-* plugins.
> build(deps): bump dependencies

- README.md
- index.js
This should land if https://github.com/nodejs/node/pull/41119 lands.
> chore: update links to style guide

- index.js
Ref: https://github.com/nodejs/node/pull/46178
> feat: add linting for "file system" vs. "filesystem"

- index.js
- package-lock.json
- package.json
This requires a small change to our configuration.
> build(deps): bump remark-lint-list-item-indent from 3.1.2 to 4.0.0

- .github/workflows/test-and-release.yml
- package-lock.json
- package.json
(builds on #473)
Will need an `NPM_TOKEN` in this repo to work.
> feat: add semantic-release automatic releases

- .github/workflows/test-and-release.yml
I don't think it will really catch anything new, but probably a good idea for a tool used in core
> ci: Add Node 22 to matrix
